### ISSUE TITLE
Running the install script per the readme will not work

### ISSUE THREAD

**Issue by niclaslindstedt** [GeeWee/reshaper-pre-commit-hook#9]
The readme states

```
curl -s https://raw.githubusercontent.com/GeeWee/reshaper-pre-commit-hook/master/install-git-hook.sh | sh (or bash, depending on your system)
```

If you **can** run your script with sh, you should. So you shouldn't advise people to run bash if they can run it with sh since it's more portable.

However, running this with sh doesn't work:

```
sh: 5: set: Illegal option -o pipefail
```

Running it with bash worked fine.

Ubuntu 18.04.

**Comment by GeeWee** [comment]
Good catch.
